import HomeCom from "@/components/home/HomeCom";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Online Grocery Shopping and Online Supermarket in India - digibasket
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCom />
    </>
  );
}
